# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@ai-sdk/provider@3.0.8" = fetchurl {
    url = "https://registry.npmjs.org/@ai-sdk/provider/-/provider-3.0.8.tgz";
    hash = "sha512-oGMAgGoQdBXbZqNG0Ze56CHjDZ1IDYOwGYxYjO5KLSlz5HiNQ9udIXsPZ61VWaHGZ5XW/jyjmr6t2xz2jGVwbQ==";
  };
  "@apidevtools/json-schema-ref-parser@11.9.3" = fetchurl {
    url = "https://registry.npmjs.org/@apidevtools/json-schema-ref-parser/-/json-schema-ref-parser-11.9.3.tgz";
    hash = "sha512-60vepv88RwcJtSHrD6MjIL6Ta3SOYbgfnkHb+ppAVK+o9mXprRtulx7VlRl3lN3bbvysAfCS7WMVfhUYemB0IQ==";
  };
  "@jsdevtools/ono@7.1.3" = fetchurl {
    url = "https://registry.npmjs.org/@jsdevtools/ono/-/ono-7.1.3.tgz";
    hash = "sha512-4JQNk+3mVzK3xh2rqd6RB4J46qUR19azEHBneZyTZM+c456qOrbbM/5xcR8huNCCcbVt7+UmizG6GuUvPvKUYg==";
  };
  "@msgpackr-extract/msgpackr-extract-darwin-arm64@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-darwin-arm64/-/msgpackr-extract-darwin-arm64-3.0.4.tgz";
    hash = "sha512-LCkGo6JDfaBhgST7UpPWgNgLINpcpabaHfyz5OBx75nUYxBsaEPxjnyNjWpeb/xBup/682QnBfRBy2/LvPutZQ==";
  };
  "@msgpackr-extract/msgpackr-extract-darwin-x64@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-darwin-x64/-/msgpackr-extract-darwin-x64-3.0.4.tgz";
    hash = "sha512-zExlW9zUJKZH/tOtVMttwjKa4Xm/3KcNjnE3dPN92uCktwavMxpgCA3MoJK/DOnTWsQgo224OaST27/mPNAf+w==";
  };
  "@msgpackr-extract/msgpackr-extract-linux-arm64@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-linux-arm64/-/msgpackr-extract-linux-arm64-3.0.4.tgz";
    hash = "sha512-dgX0P/9wGPJeHFBG+ZmhgE6bmtMt7NP5CRBGyyktpopdk/mW4POnrpQsSLtKI1dwpc+pPLuXHDh6vvskyQE/sw==";
  };
  "@msgpackr-extract/msgpackr-extract-linux-arm@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-linux-arm/-/msgpackr-extract-linux-arm-3.0.4.tgz";
    hash = "sha512-Tg3yX65f5GbtXLkrYEHE5oibZG9epyYWas7FogTTEJeDEF9JlXJzKgXaNhT3UXlTOeA+AfZpYZYZ0uPj7Cfquw==";
  };
  "@msgpackr-extract/msgpackr-extract-linux-x64@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-linux-x64/-/msgpackr-extract-linux-x64-3.0.4.tgz";
    hash = "sha512-8TNXMEjJc3QEy7R/x1INhgiU+XakDAFUzBhaz7+Rbrs8NH5UQeHQxxmzsSBJGyV6I1jW79undiQm8tOI+D+8FQ==";
  };
  "@msgpackr-extract/msgpackr-extract-win32-x64@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/@msgpackr-extract/msgpackr-extract-win32-x64/-/msgpackr-extract-win32-x64-3.0.4.tgz";
    hash = "sha512-CmCXPQrkbwExx3j946/PtHWHbYJiCRBRDl4BlkRQcJB/YOwQxJRTpoo7aTsortjgoJ1x7opzTSxn7C+ASSLVjQ==";
  };
  "@opencode-ai/plugin@1.18.4" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/plugin/-/plugin-1.18.4.tgz";
    hash = "sha512-Mkq128aLJo4E8Sb2bX8zrRlQ+I2WPaJ/n1kzaor8nTi/K/zNP4t8LGKwyMbuRoD/lhw4veSbzDOASSSypv3mcQ==";
  };
  "@opencode-ai/sdk@1.18.4" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/sdk/-/sdk-1.18.4.tgz";
    hash = "sha512-p/3P0KtWknoLvpsk8QrUzCKd4Q1A5Z3RmACEvwuQBGxnUy4AGo379lUYMgt7fczFn53079oroLuo6BosQri+HA==";
  };
  "@standard-schema/spec@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@standard-schema/spec/-/spec-1.1.0.tgz";
    hash = "sha512-l2aFy5jALhniG5HgqrD6jXLi/rUWrKvqN/qJx6yoJsgKhblVd+iqqU4RCXavm/jPityDo5TCvKMnpjKnOriy0w==";
  };
  "@types/bun@1.3.13" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.3.13.tgz";
    hash = "sha512-9fqXWk5YIHGGnUau9TEi+qdlTYDAnOj+xLCmSTwXfAIqXr2x4tytJb43E9uCvt09zJURKXwAtkoH4nLQfzeTXw==";
  };
  "@types/json-schema@7.0.15" = fetchurl {
    url = "https://registry.npmjs.org/@types/json-schema/-/json-schema-7.0.15.tgz";
    hash = "sha512-5+fP8P8MFNC+AyZCDxrB2pkZFPGzqQWUzpSeuuVLvm8VMcorNYavBqoFcxK8bQz4Qsbn4oUEEem4wDLfcysGHA==";
  };
  "@types/lodash@4.17.24" = fetchurl {
    url = "https://registry.npmjs.org/@types/lodash/-/lodash-4.17.24.tgz";
    hash = "sha512-gIW7lQLZbue7lRSWEFql49QJJWThrTFFeIMJdp3eH4tKoxm1OvEPg02rm4wCCSHS0cL3/Fizimb35b7k8atwsQ==";
  };
  "@types/node@26.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-26.1.1.tgz";
    hash = "sha512-nxAkRSVkN1Y0JC1W8ky/fTfkGsMmcrRsbx+3XoZE+rMOX71kLYTV7fLXpqud1GpbpP5TuffXFqfX7fH2GgZREw==";
  };
  "@yuansheng-kit/opencode-ys-trace" = copyPathToStore ./plugins/trace/opencode;
  "@yuansheng-kit/plugin-builder" = copyPathToStore ./tools/plugin-builder;
  "ajv-formats@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/ajv-formats/-/ajv-formats-3.0.1.tgz";
    hash = "sha512-8iUql50EUR+uUcdRQ3HDqa6EVyo3docL8g5WJ3FNcWmu62IbkGUue/pEyLBW8VGKKucTPgqeks4fIU1DA4yowQ==";
  };
  "ajv@8.20.0" = fetchurl {
    url = "https://registry.npmjs.org/ajv/-/ajv-8.20.0.tgz";
    hash = "sha512-Thbli+OlOj+iMPYFBVBfJ3OmCAnaSyNn4M1vz9T6Gka5Jt9ba/HIR56joy65tY6kx/FCF5VXNB819Y7/GUrBGA==";
  };
  "argparse@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
    hash = "sha512-8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
  };
  "bun-types@1.3.13" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.3.13.tgz";
    hash = "sha512-QXKeHLlOLqQX9LgYaHJfzdBaV21T63HhFJnvuRCcjZiaUDpbs5ED1MgxbMra71CsryN/1dAoXuJJJwIv/2drVA==";
  };
  "canonicalize@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/canonicalize/-/canonicalize-3.0.0.tgz";
    hash = "sha512-yYLfHyDMIXRyRqsKBRLX023riFLpXY2YOfdtqKXZRZy9qsfOJ9U+4F9YZL7MEzL5+ziN2x2nlBvY/Voi3EBljA==";
  };
  "cross-spawn@7.0.6" = fetchurl {
    url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
    hash = "sha512-uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
  };
  "detect-libc@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/detect-libc/-/detect-libc-2.1.2.tgz";
    hash = "sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==";
  };
  "effect@4.0.0-beta.83" = fetchurl {
    url = "https://registry.npmjs.org/effect/-/effect-4.0.0-beta.83.tgz";
    hash = "sha512-0wsak8RtgGAr9UWSbVDgJHZcUqMSvicHcvaZv1MbMM7MCGgW4Rn/137J1MHQbwYPcwYGxT/IqehFd+UbYuj78w==";
  };
  "fast-check@4.9.0" = fetchurl {
    url = "https://registry.npmjs.org/fast-check/-/fast-check-4.9.0.tgz";
    hash = "sha512-7ms6T7SybUev/PQITciI0yLM2pOSFy5zpG8Ty7tQofcVaQUvrMXp6CBwqF6fThLCLOrfBtuHAtwq6Yu4XPCllg==";
  };
  "fast-deep-equal@3.1.3" = fetchurl {
    url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
    hash = "sha512-f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
  };
  "fast-uri@3.1.4" = fetchurl {
    url = "https://registry.npmjs.org/fast-uri/-/fast-uri-3.1.4.tgz";
    hash = "sha512-8JnbkQ4juDyvYs4mgFGQqg4yCYtFDtUtmp2QIQq11ZZe5CFQ5wcqm1rqDgAh/QdMySuBnPzMUiJUNZG5N/AiQw==";
  };
  "fdir@6.5.0" = fetchurl {
    url = "https://registry.npmjs.org/fdir/-/fdir-6.5.0.tgz";
    hash = "sha512-tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==";
  };
  "find-my-way-ts@0.1.6" = fetchurl {
    url = "https://registry.npmjs.org/find-my-way-ts/-/find-my-way-ts-0.1.6.tgz";
    hash = "sha512-a85L9ZoXtNAey3Y6Z+eBWW658kO/MwR7zIafkIUPUMf3isZG0NCs2pjW2wtjxAKuJPxMAsHUIP4ZPGv0o5gyTA==";
  };
  "ini@7.0.0" = fetchurl {
    url = "https://registry.npmjs.org/ini/-/ini-7.0.0.tgz";
    hash = "sha512-ifK0CgjALofS5bkrcTy4RaQ9Vx2Knf/eLeIO+NaswQEpH1UblrtTSCIvN71qQDMq0PeQ/SSPojvEJp9vvvfr+w==";
  };
  "is-extglob@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
    hash = "sha512-SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
  };
  "is-glob@4.0.3" = fetchurl {
    url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
    hash = "sha512-xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
  };
  "isexe@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
    hash = "sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
  };
  "js-yaml@4.3.0" = fetchurl {
    url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.3.0.tgz";
    hash = "sha512-1td788aAnnZ5qs7V2QIRl1owjtYpbKt749Y3xauqQgwIIGF/xXWz1wMTEBx5O3LK3lXLVuqXPdPxj2BoFHaW9Q==";
  };
  "json-schema-to-typescript@15.0.4" = fetchurl {
    url = "https://registry.npmjs.org/json-schema-to-typescript/-/json-schema-to-typescript-15.0.4.tgz";
    hash = "sha512-Su9oK8DR4xCmDsLlyvadkXzX6+GGXJpbhwoLtOGArAG61dvbW4YQmSEno2y66ahpIdmLMg6YUf/QHLgiwvkrHQ==";
  };
  "json-schema-traverse@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
    hash = "sha512-NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
  };
  "json-schema@0.4.0" = fetchurl {
    url = "https://registry.npmjs.org/json-schema/-/json-schema-0.4.0.tgz";
    hash = "sha512-es94M3nTIfsEPisRafak+HDLfHXnKBhV3vU5eqPcS3flIWqcxJWgXHXiey3YrpaNsanY5ei1VoYEbOzijuq9BA==";
  };
  "jsonc-parser@3.3.1" = fetchurl {
    url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.3.1.tgz";
    hash = "sha512-HUgH65KyejrUFPvHFPbqOY0rsFip3Bo5wb4ngvdi1EpCYWUQDC5V+Y7mZws+DLkr4M//zQJoanu1SP+87Dv1oQ==";
  };
  "kubernetes-types@1.30.0" = fetchurl {
    url = "https://registry.npmjs.org/kubernetes-types/-/kubernetes-types-1.30.0.tgz";
    hash = "sha512-Dew1okvhM/SQcIa2rcgujNndZwU8VnSapDgdxlYoB84ZlpAD43U6KLAFqYo17ykSFGHNPrg0qry0bP+GJd9v7Q==";
  };
  "lodash@4.18.1" = fetchurl {
    url = "https://registry.npmjs.org/lodash/-/lodash-4.18.1.tgz";
    hash = "sha512-dMInicTPVE8d1e5otfwmmjlxkZoUpiVLwyeTdUsi/Caj/gfzzblBcCE5sRHV/AsjuCmxWrte2TNGSYuCeCq+0Q==";
  };
  "minimist@1.2.8" = fetchurl {
    url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
    hash = "sha512-2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
  };
  "msgpackr-extract@3.0.4" = fetchurl {
    url = "https://registry.npmjs.org/msgpackr-extract/-/msgpackr-extract-3.0.4.tgz";
    hash = "sha512-4kmO/MdyUIkLIvTPr8VHLil4AtoKIoniWPIEk5+CDy0xnWC84azhSFmuJ7PxZdsYtiP5kEeQsORAVIeMgxT+Hw==";
  };
  "msgpackr@2.0.4" = fetchurl {
    url = "https://registry.npmjs.org/msgpackr/-/msgpackr-2.0.4.tgz";
    hash = "sha512-o1C5KRmuRt+apqMr1HuGSqWStZoRBUpEsCsl15uM9VdAF1qHLtvMOU2En747EnTyEl6c4pzPewRMFF31s1CNbA==";
  };
  "multipasta@0.2.8" = fetchurl {
    url = "https://registry.npmjs.org/multipasta/-/multipasta-0.2.8.tgz";
    hash = "sha512-ZPWuMKyv0cSO29f7hozp+k6+crZbQijV8ipMvxNxRf2SwtYGTX1ZX89Kd20VV4H9Znonx+EQn+iy1wGQsJ+b+Q==";
  };
  "node-gyp-build-optional-packages@5.2.2" = fetchurl {
    url = "https://registry.npmjs.org/node-gyp-build-optional-packages/-/node-gyp-build-optional-packages-5.2.2.tgz";
    hash = "sha512-s+w+rBWnpTMwSFbaE0UXsRlg7hU4FjekKU4eyAih5T8nJuNZT1nNsskXpxmeqSK9UzkBl6UgRlnKc8hz8IEqOw==";
  };
  "opencode-ys-craft" = copyPathToStore ./plugins/craft/opencode;
  "path-key@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
    hash = "sha512-ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
  };
  "picomatch@4.0.5" = fetchurl {
    url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.5.tgz";
    hash = "sha512-RvwwcruNjI1ncT5xRakeyS9Lf8lcItv34KD+aif+VH9kduAyfYBipGh12274xtenIPZ119/R9BdTBa8gAwSh0A==";
  };
  "prettier@3.9.6" = fetchurl {
    url = "https://registry.npmjs.org/prettier/-/prettier-3.9.6.tgz";
    hash = "sha512-OpN0zzVdiaiAhxpuuj5efpIS4sY9j7bY6uR5mnj5yPzGkdkjNKSJeUThPb60Jw29QuAZgA4o+/iB49kFiaBX6g==";
  };
  "pure-rand@8.4.2" = fetchurl {
    url = "https://registry.npmjs.org/pure-rand/-/pure-rand-8.4.2.tgz";
    hash = "sha512-vvuOGgcuPJAirlHvuQw1TrOiw7ptaIXXmIbNuiNOY6lNGJJH49PQ1Kj4nd783nPdQhQdicgOjVI2yI/9BD6/Ng==";
  };
  "require-from-string@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
    hash = "sha512-Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
  };
  "shebang-command@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
    hash = "sha512-kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
  };
  "shebang-regex@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
    hash = "sha512-7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
  };
  "tinyglobby@0.2.17" = fetchurl {
    url = "https://registry.npmjs.org/tinyglobby/-/tinyglobby-0.2.17.tgz";
    hash = "sha512-wXR/dYpcqKmfWpEdZjiKJOwCNFndD0DMnrW/cYjVGttEkBfVgcLFHoNrlj47mjOVic9yyNu65alsgF4NQyTa2g==";
  };
  "toml@4.3.0" = fetchurl {
    url = "https://registry.npmjs.org/toml/-/toml-4.3.0.tgz";
    hash = "sha512-lVb8X9BsPVuH0M4BKeS91tXAmJvCjQ5UIyAbQFaxkKGyUFK2RPkhwaFSQH8vbpl1d23eu/IBH+dwVMHWaq9A5A==";
  };
  "typescript@5.9.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
    hash = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
  };
  "undici-types@8.3.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-8.3.0.tgz";
    hash = "sha512-j375ScV60dom+YkPFIfTLcOiPxkN/buHz5GobjLhixFuANaNs3C9l4GmrWqejgXWJ7BbJcFYpTEUkS1Ge8bpZQ==";
  };
  "uuid@14.0.1" = fetchurl {
    url = "https://registry.npmjs.org/uuid/-/uuid-14.0.1.tgz";
    hash = "sha512-6ZxzVpzDXDa3bJWaHilVayA+BH/1zmxCJoVgvmqJnid/gPoKHxUrS/aC/T6LGQtNHT+XHG9fXPJB4d+IrU30Ew==";
  };
  "which@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
    hash = "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
  };
  "yaml@2.9.0" = fetchurl {
    url = "https://registry.npmjs.org/yaml/-/yaml-2.9.0.tgz";
    hash = "sha512-2AvhNX3mb8zd6Zy7INTtSpl1F15HW6Wnqj0srWlkKLcpYl/gMIMJiyuGq2KeI2YFxUPjdlB+3Lc10seMLtL4cA==";
  };
  "zod@4.1.8" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.1.8.tgz";
    hash = "sha512-5R1P+WwQqmmMIEACyzSvo4JXHY5WiAFHRMg+zBZKgKS+Q1viRa0C1hmUKtHltoIFKtIdki3pRxkmpP74jnNYHQ==";
  };
}