import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import Ajv2020, { type SchemaObject } from "ajv/dist/2020";
import standaloneCode from "ajv/dist/standalone";
import addFormats from "ajv-formats";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const REPOSITORY_ROOT = resolve(import.meta.dir, "../../../..");
const SCHEMA_PATH = resolve(import.meta.dir, "ys-craft-contracts-v1.schema.json");
const GENERATED_ROOT = resolve(import.meta.dir, "generated");

function formatTypeScript(source: string, targetPath: string): string {
  const result = Bun.spawnSync({
    cmd: ["biome", "format", "--stdin-file-path", targetPath],
    cwd: REPOSITORY_ROOT,
    stdin: new TextEncoder().encode(source),
    stderr: "pipe",
    stdout: "pipe",
  });

  if (result.exitCode !== 0) {
    throw new Error(
      `Biome could not format ${targetPath}:\n${new TextDecoder().decode(result.stderr)}`,
    );
  }
  return new TextDecoder().decode(result.stdout);
}

async function generateOutputs(): Promise<ReadonlyMap<string, string>> {
  const schema = JSON.parse(await Bun.file(SCHEMA_PATH).text()) as SchemaObject & JSONSchema;
  if (typeof schema.$id !== "string") {
    throw new Error("The Craft contract schema must have a stable $id");
  }

  const outputs = new Map<string, string>();
  const typePath = resolve(GENERATED_ROOT, "types/ys-craft-contract-v1.ts");
  const generatedTypes = await compile(schema, "YuanshengCraftContractV1", {
    additionalProperties: false,
    bannerComment: [
      "/**",
      " * Generated from the canonical Yuansheng Craft JSON Schema.",
      " * Source: plugins/craft/workflows/artifacts/ys-craft-contracts-v1.schema.json",
      " * Do not edit this file directly.",
      " */",
    ].join("\n"),
    cwd: dirname(SCHEMA_PATH),
    enableConstEnums: false,
    format: false,
    unknownAny: true,
    unreachableDefinitions: true,
  });
  outputs.set(typePath, formatTypeScript(generatedTypes, typePath));

  const ajv = new Ajv2020({
    allErrors: true,
    code: {
      esm: true,
      lines: true,
      optimize: 1,
      source: true,
    },
    coerceTypes: false,
    ownProperties: true,
    removeAdditional: false,
    strict: true,
    useDefaults: false,
    validateSchema: true,
  });
  addFormats(ajv);
  ajv.addSchema(schema, schema.$id);

  const validatorsPath = resolve(GENERATED_ROOT, "validators.ts");
  const validators = [
    "// @ts-nocheck -- generated Ajv standalone code",
    "// Generated by plugins/craft/workflows/artifacts/generate.ts; do not edit.",
    standaloneCode(ajv, {
      validateYuanshengCraftContractV1: schema.$id,
    }),
  ].join("\n");
  outputs.set(validatorsPath, formatTypeScript(validators, validatorsPath));

  const indexPath = resolve(GENERATED_ROOT, "index.ts");
  const indexSource = [
    "// Generated by plugins/craft/workflows/artifacts/generate.ts; do not edit.",
    'export type * from "./types/ys-craft-contract-v1";',
    'export { validateYuanshengCraftContractV1 } from "./validators";',
    "",
  ].join("\n");
  outputs.set(indexPath, formatTypeScript(indexSource, indexPath));

  return outputs;
}

async function checkOutputs(outputs: ReadonlyMap<string, string>): Promise<void> {
  const staleFiles: string[] = [];
  for (const [path, expected] of outputs) {
    const file = Bun.file(path);
    if (!(await file.exists()) || (await file.text()) !== expected) {
      staleFiles.push(path.replace(`${REPOSITORY_ROOT}/`, ""));
    }
  }

  if (staleFiles.length > 0) {
    throw new Error(
      `Generated Craft contract files are stale. Run \`bun run craft-contracts:generate\`:\n${staleFiles.join("\n")}`,
    );
  }
}

async function writeOutputs(outputs: ReadonlyMap<string, string>): Promise<void> {
  for (const [path, source] of outputs) {
    await mkdir(dirname(path), { recursive: true });
    await Bun.write(path, source);
  }
}

export async function generateCraftContracts(mode: "check" | "write"): Promise<void> {
  const outputs = await generateOutputs();
  if (mode === "check") {
    await checkOutputs(outputs);
    return;
  }
  await writeOutputs(outputs);
}

if (import.meta.main) {
  const argument = Bun.argv[2] ?? "--write";
  if (argument !== "--write" && argument !== "--check") {
    throw new Error("Usage: generate.ts [--write|--check]");
  }
  await generateCraftContracts(argument === "--check" ? "check" : "write");
}
