import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import Ajv2020, { type SchemaObject } from "ajv/dist/2020";
import standaloneCode from "ajv/dist/standalone";
import { compile, type JSONSchema } from "json-schema-to-typescript";

interface ContractSpec {
  readonly schemaPath: string;
  readonly typeFile: string;
  readonly typeName: string;
  readonly validatorExport: string;
}

const repositoryRoot = resolve(import.meta.dir, "../..");
const generatedRoot = resolve(import.meta.dir, "src/generated");

const contractSpecs: readonly ContractSpec[] = [
  {
    schemaPath: "contracts/yuansheng-root-cause-blueprint/v1-lite/schema.json",
    typeFile: "yuansheng-root-cause-blueprint-v1-lite.ts",
    typeName: "YuanshengRootCauseBlueprintV1Lite",
    validatorExport: "validateYuanshengRootCauseBlueprintV1Lite",
  },
].sort((left, right) => left.schemaPath.localeCompare(right.schemaPath));

async function readSchema(spec: ContractSpec): Promise<SchemaObject & JSONSchema> {
  const absolutePath = resolve(repositoryRoot, spec.schemaPath);
  const source = await Bun.file(absolutePath).text();
  return JSON.parse(source) as SchemaObject & JSONSchema;
}

function formatTypeScript(source: string, targetPath: string): string {
  const result = Bun.spawnSync({
    cmd: ["biome", "format", "--stdin-file-path", targetPath],
    cwd: repositoryRoot,
    stdin: new TextEncoder().encode(source),
    stderr: "pipe",
    stdout: "pipe",
  });

  if (result.exitCode !== 0) {
    const stderr = new TextDecoder().decode(result.stderr);
    throw new Error(`Biome could not format ${targetPath}:\n${stderr}`);
  }

  return new TextDecoder().decode(result.stdout);
}

async function generateOutputs(): Promise<ReadonlyMap<string, string>> {
  const outputs = new Map<string, string>();
  const schemas = await Promise.all(contractSpecs.map(readSchema));

  for (const [index, spec] of contractSpecs.entries()) {
    const schema = schemas[index];
    if (schema === undefined) {
      throw new Error(`No Schema was loaded for ${spec.schemaPath}`);
    }

    const targetPath = resolve(generatedRoot, "types", spec.typeFile);
    const generated = await compile(schema, spec.typeName, {
      additionalProperties: false,
      bannerComment: [
        "/**",
        " * Generated from the canonical JSON Schema.",
        ` * Source: ${spec.schemaPath}`,
        " * Do not edit this file directly.",
        " */",
      ].join("\n"),
      cwd: dirname(resolve(repositoryRoot, spec.schemaPath)),
      enableConstEnums: false,
      format: false,
      unknownAny: true,
      unreachableDefinitions: true,
    });
    outputs.set(targetPath, formatTypeScript(generated, targetPath));
  }

  const ajv = new Ajv2020({
    allErrors: true,
    code: {
      esm: true,
      lines: true,
      optimize: 1,
      source: true,
    },
    coerceTypes: false,
    ownProperties: true,
    removeAdditional: false,
    strict: true,
    useDefaults: false,
    validateSchema: true,
  });

  for (const schema of schemas) {
    if (typeof schema.$id !== "string") {
      throw new Error("Every contract Schema must have a stable $id");
    }
    ajv.addSchema(schema, schema.$id);
  }

  const validatorRefs: Record<string, string> = {};
  for (const [index, spec] of contractSpecs.entries()) {
    const schema = schemas[index];
    if (schema === undefined || typeof schema.$id !== "string") {
      throw new Error(`No stable Schema ID was loaded for ${spec.schemaPath}`);
    }
    validatorRefs[spec.validatorExport] = schema.$id;
  }

  const validatorsPath = resolve(generatedRoot, "validators.ts");
  const validators = [
    "// @ts-nocheck -- generated Ajv standalone code",
    "// Generated by tools/yuansheng-root-cause-blueprint/generate.ts; do not edit.",
    standaloneCode(ajv, validatorRefs),
  ].join("\n");
  outputs.set(validatorsPath, formatTypeScript(validators, validatorsPath));

  const indexPath = resolve(generatedRoot, "index.ts");
  const indexSource = [
    "// Generated by tools/yuansheng-root-cause-blueprint/generate.ts; do not edit.",
    ...contractSpecs.map(
      (spec) =>
        `export type { ${spec.typeName} } from "./types/${spec.typeFile.replace(/\.ts$/, "")}";`,
    ),
    `export { ${contractSpecs.map((spec) => spec.validatorExport).join(", ")} } from "./validators";`,
    "",
  ].join("\n");
  outputs.set(indexPath, formatTypeScript(indexSource, indexPath));

  return outputs;
}

async function checkOutputs(outputs: ReadonlyMap<string, string>): Promise<void> {
  const staleFiles: string[] = [];

  for (const [path, expected] of outputs) {
    const file = Bun.file(path);
    if (!(await file.exists()) || (await file.text()) !== expected) {
      staleFiles.push(path.replace(`${repositoryRoot}/`, ""));
    }
  }

  if (staleFiles.length > 0) {
    throw new Error(
      `Generated contract files are stale. Run \`bun run contracts:generate\`:\n${staleFiles.join("\n")}`,
    );
  }
}

async function writeOutputs(outputs: ReadonlyMap<string, string>): Promise<void> {
  for (const [path, source] of outputs) {
    await mkdir(dirname(path), { recursive: true });
    await Bun.write(path, source);
  }
}

export async function generateContracts(mode: "check" | "write"): Promise<void> {
  const outputs = await generateOutputs();
  if (mode === "check") {
    await checkOutputs(outputs);
    return;
  }
  await writeOutputs(outputs);
}

if (import.meta.main) {
  const argument = Bun.argv[2] ?? "--write";
  if (argument !== "--write" && argument !== "--check") {
    throw new Error("Usage: generate.ts [--write|--check]");
  }
  await generateContracts(argument === "--check" ? "check" : "write");
}
